name: Publish
permissions: write-all
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Publish static site
      run: |
        mkdir -p public
        pushd public
        cp ../index.html index.html
        touch .nojekyll
        git init
        git branch -m gh-pages
        git config --global user.email "chimexjessica@outlook.com"
        git config --global user.name "augusthottie"
        git remote add origin "https://augusthottie:$TOKEN@github.com/augusthottie/blog.git"
        git add -A
        git commit -m "update site page"
        git push --force -u origin gh-pages